paths:
  uploads: uploads
  static: ''
collections_config:
  pages:
    path: ''
    name: The Vise Homepage
    icon:
    disable_url: false
    documentation:
      url: https://github.com/sockerman04/thevise-website.git
      text:
      icon: '360'
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  skills:
    path: skills
    icon: skillet
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
timezone: America/Los_Angeles
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: false
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
